name: cloudinary_dart
description: A starting point for Dart libraries or applications.
version: 0.0.1
homepage: https://www.cloudinary.com
repository: https://github.com/cloudinary/cloudinary_dart

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  crypto: ^3.0.2
  convert: ^3.0.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
